// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HousePricePrediction
{
    public partial class PricePredictMLM
    {
        /// <summary>
        /// model input class for PricePredictMLM.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Type")]
            public string Type { get; set; }

            [ColumnName(@"District")]
            public string District { get; set; }

            [ColumnName(@"Address")]
            public string Address { get; set; }

            [ColumnName(@"Area")]
            public float Area { get; set; }

            [ColumnName(@"Townhouse")]
            public bool Townhouse { get; set; }

            [ColumnName(@"Amenity")]
            public bool Amenity { get; set; }

            [ColumnName(@"Centrality")]
            public bool Centrality { get; set; }

            [ColumnName(@"Transportation")]
            public bool Transportation { get; set; }

            [ColumnName(@"LegalDocument")]
            public float LegalDocument { get; set; }

            [ColumnName(@"SellPrice")]
            public float SellPrice { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for PricePredictMLM.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("PricePredictMLM.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
