﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace HousePricePrediction
{
    public partial class TestData
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Categorical.OneHotEncoding(@"column1", @"column1")      
                                    .Append(mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"case_by_time", @"case_by_time"),new InputOutputColumnPair(@"death_by_day", @"death_by_day"),new InputOutputColumnPair(@"death_by_time", @"death_by_time"),new InputOutputColumnPair(@"recovered_by_day", @"recovered_by_day"),new InputOutputColumnPair(@"recovered_by_time", @"recovered_by_time")}))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"active_by_day", @"active_by_day"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(@"active_by_time", @"active_by_time"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"column1",@"case_by_time",@"death_by_day",@"death_by_time",@"recovered_by_day",@"recovered_by_time",@"active_by_day",@"active_by_time"}))      
                                    .Append(mlContext.Regression.Trainers.FastForest(new FastForestRegressionTrainer.Options(){NumberOfTrees=79,FeatureFraction=1F,LabelColumnName=@"case_by_day",FeatureColumnName=@"Features"}));

            return pipeline;
        }
    }
}
