// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace HousePricePrediction
{
    public partial class TestData
    {
        /// <summary>
        /// model input class for TestData.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"column1")]
            public string Column1 { get; set; }

            [ColumnName(@"case_by_day")]
            public float Case_by_day { get; set; }

            [ColumnName(@"case_by_time")]
            public float Case_by_time { get; set; }

            [ColumnName(@"active_by_day")]
            public string Active_by_day { get; set; }

            [ColumnName(@"active_by_time")]
            public string Active_by_time { get; set; }

            [ColumnName(@"death_by_day")]
            public float Death_by_day { get; set; }

            [ColumnName(@"death_by_time")]
            public float Death_by_time { get; set; }

            [ColumnName(@"recovered_by_day")]
            public float Recovered_by_day { get; set; }

            [ColumnName(@"recovered_by_time")]
            public float Recovered_by_time { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for TestData.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            public float Score { get; set; }
        }
        #endregion

        private static string MLNetModelPath = Path.GetFullPath("TestData.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
